version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk11
  pre_build:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      #- cd src
      # Install the dependencies
      #- npm install
  build:
    commands:
      # Run tests
      #- npm test
      # Remove all dependencies not relevant for production
      #- npm prune --production
      #- cd ..
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      # Copy Swagger file to S3 to be able to transform its content
      # for "deploying" it to API Gateway
      #- aws s3 cp swagger.yaml s3://$S3_BUCKET/swagger.yaml
      # Create and upload a deployment package
      #- aws cloudformation package --template-file sam-template.yaml --s3-bucket $S3_BUCKET --output-template-file sam-template-output.yaml

artifacts:
  files:
    #- sam-template-output.yaml
    - target/travel-api-1.0.0.jar
